# Generated by Django 5.0.3 on 2024-03-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('class_field', models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EditedFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=100)),
            ],
        ),
    ]
